Replace screenshots in docs
mckinsey/vizro pull request #48
Opened 2023-09-21 11:45 UTC by nadijagraca

## Description
- Replaced all screenshots to reflect navigation panel change from dropdown to accordion.
- Adjusted code examples to remove empty space on the left panel (added filter)
- Adjusted pages.md file to reflect new container structure

## Checklist

- [x] I have not referenced individuals, products or companies in any commits, directly or indirectly
- [x] I have not added data or restricted code in any commits, directly or indirectly
- [ ] I have updated the docstring of any public function/class/model changed
- [ ] I have added the PR number to the change description in the changelog fragment, e.g. `Enable feature XXX ([#1](https://github.com/mckinsey/vizro/pull/1))` (if applicable)

## Types of changes

- [x] Docs/refactoring (non-breaking change which improves codebase)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-09-21 12:47 UTC, huong-li-nguyen reviewed
I've noticed that in the floating images and styling images section we now have two cards in each example? Shall we keep it as we've had before and screenshot only the one example?
You can just adapt the screen size such that it looks nice.

But I would only use the code that is required for the output so to have two examples of the same is redundant I think

![Screenshot 2023-09-21 at 14 45 30](https://github.com/mckinsey/vizro/assets/90609403/c5dd8ff7-13e3-409f-8d43-0a59f645b8a0)

2023-09-21 12:47 UTC, huong-li-nguyen commented on vizro-core/hatch.toml
> +DASH_DEBUG = "false"
Revert change here

2023-09-21 17:45 UTC, nadijagraca commented on vizro-core/hatch.toml
> +DASH_DEBUG = "false"
Great catch! Reverted.

2023-09-21 17:51 UTC, nadijagraca commented
> I've noticed that in the floating images and styling images section we now have two cards in each example? Shall we keep it as we've had before and screenshot only the one example? You can just adapt the screen size such that it looks nice.
> 
> But I would only use the code that is required for the output so to have two examples of the same is redundant I think
> 
> ![Screenshot 2023-09-21 at 14 45 30](https://user-images.githubusercontent.com/90609403/269616167-c5dd8ff7-13e3-409f-8d43-0a59f645b8a0.png)

I did it to match the other examples that have two cards, but you are right it is a redundant.

2023-09-22 10:58 UTC, maxschulz-COL requested changes
Hero work! Found a few small things, but otherwise I think good to go from my side

2023-09-22 10:58 UTC, maxschulz-COL commented on vizro-core/docs/pages/user_guides/pages.md
> +1. The **navigation container** where you can customise your `navigation` (see [Dashboard](dashboard.md) and [Navigation](navigation.md) for more information)
```suggestion
1. The **navigation container** where you can customize your `navigation` (see [Dashboard](dashboard.md) and [Navigation](navigation.md) for more information)
```

2023-09-22 10:58 UTC, maxschulz-COL commented on vizro-core/docs/pages/user_guides/pages.md
> +    This accordinon allows navigating through the different pages.
```suggestion
    This accordion allows navigating through the different pages.
```

2023-09-22 10:58 UTC, maxschulz-COL commented on vizro-core/docs/pages/user_guides/pages.md
> +    Accordion page selector will not be added if your dashboard consists of only one page.
```suggestion
    The accordion page selector will not be added if your dashboard consists of only one page.
```

2023-09-22 18:09 UTC, huong-li-nguyen approved these changes

2023-09-23 12:56 UTC, maxschulz-COL approved these changes

2023-09-25 08:30 UTC, merged