Dev/update vizro ai dependency
mckinsey/vizro pull request #530
Opened 2024-06-17 16:40 UTC by Anna-Xiong

## Description

## Screenshot

## Notice

- [ ] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

  - I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
  - I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this contribution on behalf of the original creator(s) or their licensees.
  - I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual property rights of anyone else.
  - I have not referenced individuals, products or companies in any commits, directly or indirectly.
  - I have not added data or restricted code in any commits, directly or indirectly.

2024-06-17 16:50 UTC, maxschulz-COL approved these changes
Thanks!

2024-06-17 16:51 UTC, antonymilne commented
What is the version that actually causes a problem here? If it's 8.4.0 then a much better version specifier would be `!=8.4.0`, so that when a fixed version, say 8.4.1, comes out then you don't need to change the requirement again.

2024-06-17 16:55 UTC, Anna-Xiong commented
> What is the version that actually causes a problem here? If it's 8.4.0 then a much better version specifier would be `!=8.4.0`, so that when a fixed version, say 8.4.1, comes out then you don't need to change the requirement again.

It is the newly released version 8.4.0(  only released a few hours ago), they now have even newer version 8.4.1 i can try to see if it resolves the issue, otherwise probably let's pin under 8.4.0?

2024-06-18 07:05 UTC, huong-li-nguyen approved these changes

2024-06-18 07:05 UTC, huong-li-nguyen commented on vizro-ai/snyk/requirements.txt
> +tenacity==8.4.1
Seems like the latest version seems to be working 🥳  Do you want to apply the suggested change from @antonymilne? Should be good to go then 👍 

```suggestion
tenacity!=8.4.1
```

2024-06-18 07:05 UTC, huong-li-nguyen commented on vizro-ai/pyproject.toml
> +  "tenacity==8.4.1",  # TODO update when tenacity 8.4.0 is compatible with langchain
```suggestion
  "tenacity=!=8.4.1",  # https://github.com/langchain-ai/langchain/issues/22972
```

2024-06-18 09:03 UTC, antonymilne requested changes
If the tenacity 8.4.1 has been released and fixes the problem then there should be no need for any changes at all here and we shouldn't add a transitive dependency to our requirements. Anyone doing `pip install vizro-ai` will get the latest version of tenacity unless there's some weird conflict that we know of that forces them into the problematic 8.4.0. So best to just not do anything here I think and close the PR.

2024-06-18 10:59 UTC, huong-li-nguyen commented
> If the tenacity 8.4.1 has been released and fixes the problem then there should be no need for any changes at all here and we shouldn't add a transitive dependency to our requirements. Anyone doing `pip install vizro-ai` will get the latest version of tenacity unless there's some weird conflict that we know of that forces them into the problematic 8.4.0. So best to just not do anything here I think and close the PR.

Ah yes, main seems to be fixed now as well!

2024-06-18 10:59 UTC, closed without merging