[Tidy] Restructure vizro-ai
mckinsey/vizro pull request #561
Opened 2024-07-02 10:36 UTC by Anna-Xiong

## Description
- update `vizro ai` folder structure to separate dashboard and plot code
- common usage will be `_llm_models.py` and some files in `utils/helper.py` for now, other files has been cleaned up and restructured into `vizro_ai_charts` folder.

## Screenshot

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

  - I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
  - I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this contribution on behalf of the original creator(s) or their licensees.
  - I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual property rights of anyone else.
  - I have not referenced individuals, products or companies in any commits, directly or indirectly.
  - I have not added data or restricted code in any commits, directly or indirectly.

2024-07-11 19:57 UTC, lingyielia requested changes
Thanks for making the restructure! Left 2 comments and the rest of them looks good to me 👍

2024-07-11 19:57 UTC, lingyielia commented on vizro-ai/src/vizro_ai/vizro_ai_charts/__init__.py
Shall we name this folder as `charts` instead of `vizro_ai_charts`, as it's already under `vizro_ai`

2024-07-11 19:57 UTC, lingyielia commented on vizro-ai/tests/unit/vizro-ai/components/test_chart_selection.py
For all unit tests, let's also ensure the directory structure matching with the source code directory. For example, now the chart_selection.py is under `vizro_ai/vizro_ai_charts/components/chart_selection.py`. The tests then would be under `tests/unit/vizro_ai/vizro_ai_charts/components/test_chart_selection.py` instead of `tests/unit/vizro_ai/components/test_chart_selection.py`

2024-07-12 07:20 UTC, maxschulz-COL reviewed
Lgtm! Thanks for doing this! ❤️ 

Something that I thought about for a while, but never brought up is the following. It is by no means the scope of this PR, but I would like to hear your opinion:

Given that the dashboard code now uses Langgraph, and generally went a different direction in terms of schemas and pipelines - mainly become some of the possibilities weren't available back when we created `vizro_ai` - do you think it would make sense to:
- remove the schema manager and simplify the components to just prompts etc
- remove the pipeline manager and just put everything in one function

It would be a bit sad, because we did some of these things in the past to prepare for the dashboard creation, but we should also not get too attached to our code :P wdyt?

2024-07-26 11:18 UTC, maxschulz-COL approved these changes
⭐ Looks good to me except the one outstanding comment, which is more a typo really

2024-07-26 12:39 UTC, lingyielia approved these changes
Thanks @nadijagraca !!! LGTM

2024-07-26 12:39 UTC, lingyielia commented on vizro-ai/tests/unit/vizro-ai/plot/utils/test_safeguard_code.py
>  import re
To match with the source code folder name: `_utils`

2024-07-27 06:54 UTC, lingyielia commented on vizro-ai/src/vizro_ai/vizro_ai_charts/components/custom_chart_wrap.py
> +from vizro_ai.vizro_ai_charts.components import VizroAiComponentBase
to address in another PR

2024-07-27 06:54 UTC, lingyielia commented on vizro-ai/tests/unit/vizro-ai/plot/utils/test_safeguard_code.py
>  import re
To address in another PR

2024-07-27 06:55 UTC, merged