[QA] Score tests improvements
mckinsey/vizro pull request #935
Opened 2024-12-24 12:57 UTC by l0uden

## Description

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

    - I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
    - I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorized to submit this contribution on behalf of the original creator(s) or their licensees.
    - I certify that the use of this contribution as authorized by the Apache 2.0 license does not violate the intellectual property rights of anyone else.
    - I have not referenced individuals, products or companies in any commits, directly or indirectly.
    - I have not added data or restricted code in any commits, directly or indirectly.

2025-01-07 10:53 UTC, petar-qb approved these changes
I like these enhancements Alexey. There are a few comments, but other than that, it's all good

2025-01-07 10:53 UTC, petar-qb commented on vizro-ai/tests/score/test_dashboard.py
Do you think there's room for improvement in the following implementation:
```
    pages_exist = [1 if dashboard.pages else 0]
    pages_exist_report = bool(pages_exist[0])
    pages_num = [1 if len(dashboard.pages) == len(config["pages"]) else 0]
    pages_num_report = [f'{len(config["pages"])} page(s) for dashboard is {bool(pages_num[0])}']
    
    ...

    pages_exist.extend(pages_num)

    ...

    {"score_name": "pages_score", "weight": 0.2, "score": sum(pages_exist) / len(pages_exist)},
```

It's a bit unintuitive of how it works as `pages_exist` is a list of two elements where the first element defines is there `any` pages in the result dashboard, and the second element defines is the number of pages of the result dashboard correct or not. 
First, I don't see any value from the `pages_exist` metric. If pages don't exist, all other score tests will fail so we will know that something isn't working correctly. I see more value from `pages_num`, and I would calculate it as:
`[len(config["pages"]) / len(dashboard.pages)]`. So, the new pages_num will be a float between 0-1 (currently it's 0 or 1)

If we really want to keep `pages_exist`, then I would separate it from the `pages_num` metric score calculation as it's unintuitive to understand just my reading the code.

2025-01-09 03:20 UTC, lingyielia requested changes
Wow I really like this whole Score tests logic you created! 💯  I think it's ready to be checked while we touch the vizro-ai code, and can help track the performance more easily.

I just have some minor questions and suggestions. Overall it's really cool!

2025-01-09 03:20 UTC, lingyielia commented on vizro-ai/tests/score/prompts.py
@petar-qb good point that we might want to differentiate the easy/medium/complex further. Please add your thoughts too, but maybe we could structure the prompts like:

easy: could be extremely simple - one page with 1 line chart, 1 table, 1 card, and 1 filter. Layout could be something simple like "align chart, table, card horizontally"

medium: 3 pages with different combinations (like what you did for medium right now). The key is: the prompt is long, but the requirements are clear (meaning the llm needs to remember to perform a lot of tasks, but at least those tasks are clearly defined)

complex: it could vary on top of the medium prompt, by 
1) making some requirements vague (e.g., "The chart is an scatter plot showing life expectancy vs. GDP per capita by country. Life expectancy on the y axis, GDP per capita on the x axis, and colored by continent." --> "I'd like to see the relationship between life expectancy vs. GDP")
2) adding some noise (e.g., "adding a download button", which is not implemented in Vizro-AI yet), adding noise would increase difficulty because llm is more likely to hallucinate

2025-01-09 09:25 UTC, petar-qb commented on vizro-ai/tests/score/prompts.py
@lingyielia, I really like your suggestion to build the complex_prompt on top of the medium_prompt by making some requirements intentionally vague and by making additional complexity. Here’s a list of ideas for introducing complexity, organised from easiest to hardest in my opinion:

- Adding a download button (already mentioned),
- Adding a filter interaction action,
- Creating a filter with a specific selector,
- Introducing a parameter,
- Structuring the layout using tabs and containers,
- Organising pages with a custom navigation bar,
- Using dynamic data,
- Designing a custom graph, table, or figure,
- Building custom component,
- Implementing a custom action.

I hope this will help to create a complex_prompt (I know that some of these suggestions probably belong to something like super_complex_prompt 😄).

2025-01-16 16:54 UTC, l0uden commented on vizro-ai/tests/score/prompts.py
> +Add 3 filters to filter the line chart by companies.
Changed this prompt

2025-01-16 16:54 UTC, l0uden commented on vizro-ai/tests/score/prompts.py
> +<Page 4>
Changed this prompt

2025-01-16 16:54 UTC, l0uden commented on vizro-ai/tests/score/prompts.py
> +<Page 3>
Changed this prompt

2025-01-16 16:59 UTC, l0uden commented on vizro-ai/tests/score/prompts.py
Thanks for the useful thoughts!
Right now the logic of the tests is checking `filter` controls and `graph`, `card` and  `ag_grid` components.
So to make score not equal to `1.0` this options should be created not as we expected.
Anyway, it hope that my new prompt includes a lot from your suggestions and will help us not only now but also in future.

2025-01-16 16:59 UTC, l0uden commented on vizro-ai/tests/score/test_dashboard.py
> +                    "controls": [Control(type="filter"), Control(type="filter"), Control(type="filter")],
Done

2025-01-16 17:00 UTC, l0uden commented on vizro-ai/tests/score/test_dashboard.py
I think that is a good idea. Thanks! Reworked it

2025-01-16 17:01 UTC, l0uden commented on .github/workflows/test-score-vizro-ai.yml
> +    - cron: "30 10 * * 1" # run every Monday at 10:30 UTC
In discussion with @Joseph-Perkins , we decided to add this to have more data over the time

2025-01-16 17:02 UTC, l0uden commented on .github/workflows/test-score-vizro-ai.yml
> +          head -n 1 Report-3.12-/report_model_gpt-4o-mini_pypi.csv > report-aggregated-${{ steps.date.outputs.date }}.csv && tail -n+2 -q */*.csv >> report-aggregated-${{ steps.date.outputs.date }}.c
Thanks! Changed

2025-01-17 09:25 UTC, petar-qb commented on vizro-ai/tests/score/prompts.py
New prompts look much better now @l0uden 🚀 If we ever need more complex prompts, we can always refer to this thread which has lots of really complex suggestions.

2025-01-17 09:25 UTC, petar-qb commented on vizro-ai/tests/score/test_dashboard.py
> +# in this case in should be 1.0.
```suggestion
# in this case it should be 1.0.
```

2025-01-17 09:25 UTC, petar-qb commented on vizro-ai/tests/score/test_dashboard.py
> +    )
In input text prompts, there's a lot of layout logic described, but it's not tested. Should we test the layout too?

2025-01-17 09:25 UTC, petar-qb commented on vizro-ai/tests/score/test_dashboard.py
> +
A few questions here:

1. Intuitively, the `score_name` variable name looks more like a string. Do you think that renaming it to something like:
`def score_calculator(metric_scores: list[int]):` makes more sense? 

2. Also, is the `score_name` always a list of ints?
3. Why do you assing `1.0` if `len(score_name) != 0`? 
4. Why float score `1.0` is mixed with integers in this file `1`? Does it make sense to align it?

2025-01-17 09:25 UTC, petar-qb commented on vizro-ai/tests/score/test_dashboard.py
> +    )
If it's too complex and unnecessary to do so right now, let's add a `# TODO:` somewhere.

2025-01-17 09:25 UTC, petar-qb commented on .github/workflows/test-score-vizro-ai.yml
> +      - main
Don't forget to remove this before merging

2025-01-17 09:25 UTC, petar-qb commented on vizro-ai/tests/score/prompts.py
New prompts look much better now @l0uden 🚀 If we ever need more complex prompts, we can always refer to this thread which has lots of really complex suggestions.

One question: I saw a lot of layout logic described in the prompts, but this is not tested in the score tests.  Should these tests be added or if it's too complex or unnecessary we can add a `# TODO:` for that.

2025-01-17 11:49 UTC, l0uden commented on vizro-ai/tests/score/test_dashboard.py
> +    )
For now it was decided to do it in future. Added TODO.

2025-01-17 11:49 UTC, l0uden commented on vizro-ai/tests/score/test_dashboard.py
> +
1. Yes, thanks for suggestion

2. Yes

3. I've tried to explain it in the comment to the function `If len() is 0, it means that nothing was entered for this score in config, in this case it should be 1.0.`. E.g. if page doesn't have any `controls`, the calculation of `contols_types` will return empty `[]`, in this case we need to replace it with a score value. If it will be 0, it will affect total score, will make it lower. By setting value to 1.0 we assume that everything is correct.

4. Make sense, I will use `int` everywhere

2025-01-17 12:42 UTC, petar-qb commented on vizro-ai/tests/score/prompts.py
I referenced this thread link in the PR description so we don't forget the list of potential complexity prompt improvements.

@lingyielia Feel free to resolve this conversation when you're okay with the prompt inputs. 😃

2025-01-17 12:44 UTC, petar-qb commented on vizro-ai/tests/score/test_dashboard.py
> +
Great, thanks for addressing and explanation!

2025-01-17 18:07 UTC, lingyielia commented on vizro-ai/tests/score/prompts.py
Thanks for the change! I think it's clear to understand the difficulties of each prompt now. We can start to trace the performance change over time.

In the future PRs, we could think of ways to standardize the prompts more. For example,

simple_prompt: "some simple requests"
medium_prompt = simple_prompt + "some additional requests"
complex = medium_prompt + "some really difficult requests"
(This is just for thinking about possible future improvement. )

For now, I'm happy to merge this current version! 🎉

2025-01-17 18:08 UTC, lingyielia approved these changes
Great improvement! 🎉

2025-01-20 11:29 UTC, maxschulz-COL approved these changes
Did a light review, looks good! I think this is going in the right direction! Left a few small comments. ⭐ 💯 

In general I think my main comments are:
1. Make adding tests as easy as possible (ideally just another prompt + expectation pair, nothing else)
2. Make adding and removing models etc as easy as possible (ideally just some test parametrization or so)
3. make the complexity of the dashboard a column in the report, and allow for individual names for newly added tests (such that we can have in the furture smth like, `easy_1`, `easy_2`,`easy_abc`, etc.

Other than that, I think it's exciting!

2025-01-20 11:29 UTC, maxschulz-COL commented on vizro-ai/hatch.toml
> +test-score = "pytest -vs tests/score --headless {args}"
Do you think it would make sense to add a comment above on where to enter the API key. When I run the above command, then all tests fail, but only because the API key does not work

2025-01-20 11:29 UTC, maxschulz-COL commented on vizro-ai/tests/score/prompts.py
> +Using export button I want to export data to csv
is that even possible @lingyielia? I am not sure the json schema for the button actually includes possible custom actions?

2025-01-20 11:29 UTC, maxschulz-COL commented on vizro-ai/tests/score/test_dashboard.py
> +        "gpt-4o-mini",
what about `gpt-40` (not mini)?

2025-01-20 11:29 UTC, maxschulz-COL commented on vizro-ai/tests/score/test_dashboard.py
> +def test_medium_dashboard(dash_duo, model_name):
Why do we need individual tests for easy, medium and complex dashboards? Should this not be another parameter to a single test?

In general I have mentioned this before, I think it would be good to not have three specific dashboards, but rather any number of dashboards that belong to a tier (three tiers are fine). In the future we could then easily add more by adding simply a new pair of prompt + expectation, that should be the aim.

2025-01-20 11:29 UTC, maxschulz-COL commented on vizro-ai/tests/score/prompts.py
I just found this tread, I agree very much with what is being said. Thanks @lingyielia for providing the framework.

(ignore my comment on the button prompt, I understand now why it's there.

So we say complex is:
1. Medium prompt + noise
2. Medium prompt + hard things (complex layouts, complex filters, in future: parameters, pre-defined actions, generally Petar's list

Did I catch that more or less right?

2025-01-22 14:27 UTC, l0uden commented on vizro-ai/tests/score/test_dashboard.py
> +def test_medium_dashboard(dash_duo, model_name):
Done

2025-02-04 10:44 UTC, maxschulz-COL approved these changes
⭐ Well done ⭐ 

I think this is much better, and looks much more usable. PLease address the outstanding comments still, but I think its almost there.

Could we add more models in the parametrization?

2025-02-04 10:44 UTC, maxschulz-COL commented on vizro-ai/tests/e2e/test_dashboard.py
> +def test_dashboard_anthropic(dash_duo, model_name, tier_type, prompt_name, prompt_text, expected_config, dfs):  # noqa: PLR0913
Remind me quickly, why is this test separate from the above, and not parametrized with the above?

2025-02-04 12:23 UTC, l0uden commented on vizro-ai/tests/e2e/test_dashboard.py
> +def test_dashboard_anthropic(dash_duo, model_name, tier_type, prompt_name, prompt_text, expected_config, dfs):  # noqa: PLR0913
I did it because anthropic can't build even the medium prompt. I think the easy one is ok for it to be tested.

2025-02-04 12:23 UTC, l0uden commented
> ⭐ Well done ⭐
> 
> I think this is much better, and looks much more usable. PLease address the outstanding comments still, but I think its almost there.
> 
> Could we add more models in the parametrization?

Sure, added more

2025-02-04 12:55 UTC, l0uden commented on vizro-ai/hatch.toml
> +test-score = "pytest -vs tests/score --headless {args}"
Added

2025-02-04 14:16 UTC, merged